services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    container_name: nlw-agents-pg
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    ports:
      - "54323:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  nlw-agents-server:
    build: .
    container_name: nlw-agents-server
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_URL: postgresql://docker:docker@nlw-agents-pg:5432/agents
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - nlw-agents-pg
